[package]
name = "common"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[features]
arm9 = []
arm11 = []

[dependencies]
bitflags = "1.1.0"
font8x8 = { version = "0.2.5", default_features = false, features = ["unicode"] }
